# Generated by Django 3.2.12 on 2022-08-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shydb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shydb',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shydb',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
