# Generated by Django 3.2.12 on 2022-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200628_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='favicon',
            field=models.URLField(blank=True),
        ),
    ]
