# Generated by Django 3.2.12 on 2022-07-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211117_0217'),
        ('core', '0009_auto_20220701_0534'),
    ]

    operations = [
    ]
