# Generated by Django 3.2.12 on 2022-09-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220624_0744'),
        ('core', '0010_merge_0009_auto_20211117_0217_0009_auto_20220701_0534'),
    ]

    operations = [
    ]
